import json
import platform as platform_module
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List

from mdns_helpers.models import AppConfig, SiteConfig


SUPPORTED_PLATFORMS = {"macos", "ubuntu"}


@dataclass
class GeneratedArtifacts:
    platform_name: str
    files: Dict[Path, str]
    summary: str


def detect_platform() -> str:
    system = platform_module.system().lower()
    if system == "darwin":
        return "macos"
    if system == "linux":
        return "ubuntu"
    raise ValueError("unsupported platform '{0}'".format(system))


def generate_artifacts(config: AppConfig, platform_name: str) -> GeneratedArtifacts:
    if platform_name == "auto":
        platform_name = detect_platform()
    if platform_name not in SUPPORTED_PLATFORMS:
        raise ValueError(
            "unsupported platform '{0}'; supported: macos, ubuntu".format(platform_name)
        )

    files: Dict[Path, str] = {}
    root = config.output_dir / platform_name

    dns_config_path = _dns_config_path(config, platform_name)
    proxy_config_path = _proxy_config_path(config, platform_name)

    files[root / "dns" / "Corefile"] = _render_corefile(config, dns_config_path)
    files[root / "proxy" / "Caddyfile"] = _render_caddyfile(config, proxy_config_path)
    files[root / "inventory" / "sites.json"] = _render_inventory(config, platform_name)
    files[root / "deployment" / "README.generated.md"] = _render_generated_readme(
        config, platform_name, dns_config_path, proxy_config_path
    )

    if platform_name == "ubuntu":
        files[root / "services" / "coredns.service"] = _render_coredns_systemd(
            config, dns_config_path
        )
        files[root / "services" / "caddy.service"] = _render_caddy_systemd(
            config, proxy_config_path
        )
    else:
        files[root / "services" / "io.charley.coredns.plist"] = _render_coredns_plist(
            config, dns_config_path
        )
        files[root / "services" / "io.charley.caddy.plist"] = _render_caddy_plist(
            config, proxy_config_path
        )

    if config.mdns_enabled:
        if platform_name == "ubuntu":
            for site in _enabled_sites(config):
                files[root / "mdns" / "{0}.service".format(site.name)] = _render_avahi_service(
                    site
                )
        else:
            for site in _enabled_sites(config):
                files[root / "mdns" / "{0}.plist".format(site.name)] = _render_dns_sd_plist(
                    site, config
                )

    summary = _render_summary(config, platform_name, root)
    return GeneratedArtifacts(platform_name=platform_name, files=files, summary=summary)


def write_artifacts(artifacts: GeneratedArtifacts) -> List[Path]:
    written = []
    for path, content in artifacts.files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        written.append(path)
    return written


def _enabled_sites(config: AppConfig) -> List[SiteConfig]:
    return [site for site in config.sites if site.enabled]


def _dns_config_path(config: AppConfig, platform_name: str) -> str:
    if config.dns_config_path:
        return config.dns_config_path
    if platform_name == "ubuntu":
        return "/etc/coredns/Corefile"
    return "/usr/local/etc/coredns/Corefile"


def _proxy_config_path(config: AppConfig, platform_name: str) -> str:
    if config.proxy_config_path:
        return config.proxy_config_path
    if platform_name == "ubuntu":
        return "/etc/caddy/Caddyfile"
    return "/usr/local/etc/caddy/Caddyfile"


def _dns_binary(config: AppConfig, platform_name: str) -> str:
    if config.dns_binary:
        return config.dns_binary
    if platform_name == "ubuntu":
        return "/usr/local/bin/coredns"
    return "/opt/homebrew/bin/coredns"


def _proxy_binary(config: AppConfig, platform_name: str) -> str:
    if config.proxy_binary:
        return config.proxy_binary
    if platform_name == "ubuntu":
        return "/usr/bin/caddy"
    return "/opt/homebrew/bin/caddy"


def _render_corefile(config: AppConfig, dns_config_path: str) -> str:
    host_lines = [
        "        {0} {1}".format(config.host_ipv4, site.hostname)
        for site in _enabled_sites(config)
    ]
    lines = [
        "# Generated by mdns-helpers",
        "{0} {{".format(config.domain),
        "    hosts {",
        *(host_lines or ["        # No enabled sites"]),
        "        fallthrough",
        "    }",
        "    log",
        "    errors",
        "}",
        "",
        ".:53 {",
        "    forward . /etc/resolv.conf",
        "    cache 30",
        "    log",
        "    errors",
        "}",
        "",
        "# Intended deploy path: {0}".format(dns_config_path),
    ]
    return "\n".join(lines).rstrip() + "\n"


def _render_caddyfile(config: AppConfig, proxy_config_path: str) -> str:
    blocks = ["# Generated by mdns-helpers", ""]
    for site in _enabled_sites(config):
        blocks.append("{0} {{".format(site.hostname))
        blocks.append("    encode gzip zstd")
        if site.kind == "static_dir":
            blocks.append("    root * {0}".format(site.source))
            if site.directory_listing:
                blocks.append("    file_server browse")
            else:
                blocks.append("    file_server")
            blocks.append("    try_files {path} {path}/ /index.html")
        else:
            blocks.append("    reverse_proxy {0}".format(site.upstream))
        blocks.append("}")
        blocks.append("")
    blocks.append("# Intended deploy path: {0}".format(proxy_config_path))
    return "\n".join(blocks).rstrip() + "\n"


def _render_inventory(config: AppConfig, platform_name: str) -> str:
    payload = {
        "platform": platform_name,
        "domain": config.domain,
        "host_ipv4": config.host_ipv4,
        "sites": [
            {
                "name": site.name,
                "hostname": site.hostname,
                "kind": site.kind,
                "enabled": site.enabled,
                "source": site.source,
                "upstream": site.upstream,
            }
            for site in config.sites
        ],
    }
    return json.dumps(payload, indent=2, sort_keys=False) + "\n"


def _render_generated_readme(
    config: AppConfig, platform_name: str, dns_config_path: str, proxy_config_path: str
) -> str:
    mdns_note = "enabled" if config.mdns_enabled else "disabled"
    lines = [
        "# Generated deployment notes",
        "",
        "- Platform: {0}".format(platform_name),
        "- Domain: {0}".format(config.domain),
        "- Host IP: {0}".format(config.host_ipv4),
        "- DNS backend: {0}".format(config.dns_backend),
        "- Proxy backend: {0}".format(config.proxy_backend),
        "- mDNS advertisement: {0}".format(mdns_note),
        "",
        "## Deploy paths",
        "",
        "- Copy `dns/Corefile` to `{0}`".format(dns_config_path),
        "- Copy `proxy/Caddyfile` to `{0}`".format(proxy_config_path),
        "- Install the generated service file from `services/` for this platform.",
        "",
        "## Enabled sites",
        "",
    ]
    for site in _enabled_sites(config):
        target = site.source if site.kind == "static_dir" else site.upstream
        lines.append("- `{0}` -> `{1}` ({2})".format(site.hostname, target, site.kind))
    return "\n".join(lines).rstrip() + "\n"


def _render_coredns_systemd(config: AppConfig, dns_config_path: str) -> str:
    return """[Unit]
Description=CoreDNS local resolver generated by mdns-helpers
After=network-online.target
Wants=network-online.target

[Service]
ExecStart={binary} -conf {config}
ExecReload=/bin/kill -USR1 $MAINPID
Restart=on-failure
AmbientCapabilities=CAP_NET_BIND_SERVICE

[Install]
WantedBy=multi-user.target
""".format(binary=_dns_binary(config, "ubuntu"), config=dns_config_path)


def _render_caddy_systemd(config: AppConfig, proxy_config_path: str) -> str:
    return """[Unit]
Description=Caddy local proxy generated by mdns-helpers
After=network-online.target
Wants=network-online.target

[Service]
ExecStart={binary} run --config {config} --adapter caddyfile
ExecReload={binary} reload --config {config} --adapter caddyfile
Restart=on-failure
AmbientCapabilities=CAP_NET_BIND_SERVICE

[Install]
WantedBy=multi-user.target
""".format(binary=_proxy_binary(config, "ubuntu"), config=proxy_config_path)


def _render_coredns_plist(config: AppConfig, dns_config_path: str) -> str:
    return """<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>io.charley.coredns</string>
  <key>ProgramArguments</key>
  <array>
    <string>{binary}</string>
    <string>-conf</string>
    <string>{config}</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
</dict>
</plist>
""".format(binary=_dns_binary(config, "macos"), config=dns_config_path)


def _render_caddy_plist(config: AppConfig, proxy_config_path: str) -> str:
    return """<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>io.charley.caddy</string>
  <key>ProgramArguments</key>
  <array>
    <string>{binary}</string>
    <string>run</string>
    <string>--config</string>
    <string>{config}</string>
    <string>--adapter</string>
    <string>caddyfile</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
</dict>
</plist>
""".format(binary=_proxy_binary(config, "macos"), config=proxy_config_path)


def _render_avahi_service(site: SiteConfig) -> str:
    title = site.hostname.split(".", 1)[0]
    return """<?xml version="1.0" standalone='no'?>
<!DOCTYPE service-group SYSTEM "avahi-service.dtd">
<service-group>
  <name replace-wildcards="yes">{title}</name>
  <service>
    <type>_http._tcp</type>
    <port>80</port>
  </service>
</service-group>
""".format(title=title)


def _render_dns_sd_plist(site: SiteConfig, config: AppConfig) -> str:
    label = "io.charley.mdns.{0}".format(site.name)
    title = site.hostname.split(".", 1)[0]
    return """<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>{label}</string>
  <key>ProgramArguments</key>
  <array>
    <string>/usr/bin/dns-sd</string>
    <string>-R</string>
    <string>{title}</string>
    <string>{service_type}</string>
    <string>local</string>
    <string>80</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
</dict>
</plist>
""".format(label=label, title=title, service_type=config.mdns_service_type)


def _render_summary(config: AppConfig, platform_name: str, root: Path) -> str:
    lines = [
        "Platform: {0}".format(platform_name),
        "Output: {0}".format(root),
        "Domain: {0}".format(config.domain),
        "Host IP: {0}".format(config.host_ipv4),
        "Enabled sites: {0}/{1}".format(
            len(_enabled_sites(config)), len(config.sites)
        ),
        "",
    ]
    for site in config.sites:
        target = site.source if site.kind == "static_dir" else site.upstream
        status = "enabled" if site.enabled else "disabled"
        lines.append(
            "- {0}: {1} -> {2} ({3})".format(
                site.name, site.hostname, target, status
            )
        )
    return "\n".join(lines)
